//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpamStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gasolineras
    {
        public byte GasolineraID { get; set; }
        public string RazonSocial { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
