//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpamStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gastos_Viaje
    {
        public byte ViajeID { get; set; }
        public string NumeroFactura { get; set; }
        public int MontoFactura { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Viajes Viajes { get; set; }
    }
}
