//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpamStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viajes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Viajes()
        {
            this.Gastos_Viaje = new HashSet<Gastos_Viaje>();
        }
    
        public byte ViajeID { get; set; }
        public string SerialNumber { get; set; }
        public string EmployeeID { get; set; }
        public byte RutaID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Camiones Camiones { get; set; }
        public virtual Conductores Conductores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gastos_Viaje> Gastos_Viaje { get; set; }
        public virtual Rutas Rutas { get; set; }
    }
}
